"""Static game data (starter region, coordinates, rolling stock, services).

PR 2: extracted from train_idle_monolith.py to keep the monolith smaller and to
make future region expansion easier.
"""

from __future__ import annotations

from train_idle.models import ServiceTemplate, TrainModel

# Devon bundle + map coords
DEVON_BUNDLE = {
    'region_id': 'devon',
    'version': 'v056-scopeAplus',
    'nodes': [
        {'id': 'PLY', 'name': 'Plymouth', 'kind': 'STATION', 'size': 4, 'major': True},
        {'id': 'NWP', 'name': 'Newton Abbot', 'kind': 'STATION', 'size': 3, 'major': False},
        {'id': 'EXD', 'name': 'Exeter St Davids', 'kind': 'STATION', 'size': 4, 'major': True},
        {'id': 'TIV', 'name': 'Tiverton Parkway', 'kind': 'STATION', 'size': 2, 'major': True},
        {'id': 'TAU', 'name': 'Taunton', 'kind': 'STATION', 'size': 3, 'major': True},
        {'id': 'BRI', 'name': 'Bristol Temple Meads', 'kind': 'STATION', 'size': 5, 'major': True},
        {'id': 'CDI', 'name': 'Crediton', 'kind': 'STATION', 'size': 2, 'major': False},
        {'id': 'YEO', 'name': 'Yeoford', 'kind': 'STATION', 'size': 2, 'major': False},
        {'id': 'EGG', 'name': 'Eggesford', 'kind': 'STATION', 'size': 2, 'major': False},
        {'id': 'BNP', 'name': 'Barnstaple', 'kind': 'STATION', 'size': 3, 'major': False},
        {'id': 'OKE', 'name': 'Okehampton', 'kind': 'STATION', 'size': 2, 'major': False},
        {'id': 'EXM', 'name': 'Exmouth', 'kind': 'STATION', 'size': 2, 'major': False},
        {'id': 'TOP', 'name': 'Topsham', 'kind': 'STATION', 'size': 1, 'major': False},
        {'id': 'DIG', 'name': 'Digby & Sowton', 'kind': 'STATION', 'size': 1, 'major': False},
        {'id': 'TQY', 'name': 'Torquay', 'kind': 'STATION', 'size': 2, 'major': False},
        {'id': 'PGN', 'name': 'Paignton', 'kind': 'STATION', 'size': 2, 'major': False},
        {'id': 'HON', 'name': 'Honiton', 'kind': 'STATION', 'size': 2, 'major': False},
        {'id': 'EXD_W', 'name': 'Exeter West Jn', 'kind': 'JUNCTION'},
        {'id': 'CWB', 'name': 'Cowley Bridge Jn', 'kind': 'JUNCTION'},
        {'id': 'YEO_JN', 'name': 'Yeoford Jn', 'kind': 'JUNCTION'},
        {'id': 'TAU_W', 'name': 'Taunton West Jn', 'kind': 'JUNCTION'},
        {'id': 'EXJ', 'name': 'Exmouth Jn', 'kind': 'JUNCTION'},
    ],
    'edges': [
        {
            'id': 'E_PLY_NWP',
            'a': 'PLY',
            'b': 'NWP',
            'km': 42,
            'speed_kmh': 125,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_NWP_EXDW',
            'a': 'NWP',
            'b': 'EXD_W',
            'km': 32,
            'speed_kmh': 125,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_EXDW_EXD',
            'a': 'EXD_W',
            'b': 'EXD',
            'km': 2.0,
            'speed_kmh': 60,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_EXDW_CWB',
            'a': 'EXD_W',
            'b': 'CWB',
            'km': 3.0,
            'speed_kmh': 70,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_CWB_EXD',
            'a': 'CWB',
            'b': 'EXD',
            'km': 1.5,
            'speed_kmh': 50,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_CWB_CDI',
            'a': 'CWB',
            'b': 'CDI',
            'km': 7.5,
            'speed_kmh': 80,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_CDI_YEOJN',
            'a': 'CDI',
            'b': 'YEO_JN',
            'km': 6.5,
            'speed_kmh': 85,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_YEOJN_YEO',
            'a': 'YEO_JN',
            'b': 'YEO',
            'km': 0.5,
            'speed_kmh': 40,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_YEOJN_EGG',
            'a': 'YEO_JN',
            'b': 'EGG',
            'km': 14.0,
            'speed_kmh': 85,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_EGG_BNP',
            'a': 'EGG',
            'b': 'BNP',
            'km': 25.0,
            'speed_kmh': 85,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_YEOJN_OKE',
            'a': 'YEO_JN',
            'b': 'OKE',
            'km': 25.0,
            'speed_kmh': 90,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_EXD_TIV',
            'a': 'EXD',
            'b': 'TIV',
            'km': 27,
            'speed_kmh': 125,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_TIV_TAUW',
            'a': 'TIV',
            'b': 'TAU_W',
            'km': 48,
            'speed_kmh': 125,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_TAUW_TAU',
            'a': 'TAU_W',
            'b': 'TAU',
            'km': 2.5,
            'speed_kmh': 60,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_TAUW_BRI',
            'a': 'TAU_W',
            'b': 'BRI',
            'km': 79,
            'speed_kmh': 125,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_EXD_EXJ',
            'a': 'EXD',
            'b': 'EXJ',
            'km': 3.0,
            'speed_kmh': 70,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_EXJ_DIG',
            'a': 'EXJ',
            'b': 'DIG',
            'km': 5.5,
            'speed_kmh': 90,
            'tracks': 2,
            'bidir': True,
        },
        {
            'id': 'E_DIG_TOP',
            'a': 'DIG',
            'b': 'TOP',
            'km': 7.0,
            'speed_kmh': 90,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_TOP_EXM',
            'a': 'TOP',
            'b': 'EXM',
            'km': 7.0,
            'speed_kmh': 90,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_NWP_TQY',
            'a': 'NWP',
            'b': 'TQY',
            'km': 23.0,
            'speed_kmh': 90,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_TQY_PGN',
            'a': 'TQY',
            'b': 'PGN',
            'km': 6.0,
            'speed_kmh': 80,
            'tracks': 1,
            'bidir': True,
        },
        {
            'id': 'E_EXD_HON',
            'a': 'EXD',
            'b': 'HON',
            'km': 25.0,
            'speed_kmh': 100,
            'tracks': 1,
            'bidir': True,
        },
    ],
}

PANEL_POS_DEFAULT: dict[str, tuple[int, int]] = {
    'PLY': (2, 8),
    'NWP': (22, 8),
    'EXD_W': (38, 8),
    'EXD': (52, 8),
    'TIV': (68, 8),
    'TAU_W': (86, 8),
    'TAU': (96, 8),
    'BRI': (112, 6),
    'CWB': (44, 10),
    'CDI': (44, 14),
    'YEO_JN': (44, 17),
    'YEO': (58, 17),
    'EGG': (44, 20),
    'BNP': (44, 23),
    'OKE': (30, 20),
    'EXJ': (60, 10),
    'DIG': (70, 12),
    'TOP': (78, 14),
    'EXM': (88, 16),
    'TQY': (22, 12),
    'PGN': (22, 15),
    'HON': (74, 5),
}

# Rolling stock + services
TRAIN_MODELS: dict[str, TrainModel] = {
    'dmu': TrainModel('dmu', 'Local DMU (2-car)', 'passenger', cost=450, cruise_kmh=85, capacity=150),
    'emu': TrainModel('emu', 'Regional EMU', 'passenger', cost=900, cruise_kmh=105, capacity=230),
    'hstk': TrainModel('hstk', 'Intercity Set', 'passenger', cost=2600, cruise_kmh=145, capacity=360),
    'fr8': TrainModel('fr8', 'Freight Loco', 'freight', cost=1200, cruise_kmh=90, capacity=900),
    'hhv': TrainModel('hhv', 'Heavy Hauler', 'freight', cost=4200, cruise_kmh=75, capacity=1800),
}

SERVICE_TEMPLATES: list[ServiceTemplate] = [
    ServiceTemplate(
        'sw_local',
        'SW Local: Plymouth–Newton Abbot–Exeter–Tiverton–Taunton',
        'passenger',
        'local',
        ['PLY', 'NWP', 'EXD', 'TIV', 'TAU'],
        fare_per_km=0.09,
        target_headway_s=3600,
        grace_pct=0.10,
    ),
    ServiceTemplate(
        'sw_fast',
        'SW Fast: Plymouth–Exeter–Taunton (Express)',
        'passenger',
        'express',
        ['PLY', 'EXD', 'TAU'],
        fare_per_km=0.10,
        target_headway_s=7200,
        grace_pct=0.10,
    ),
    ServiceTemplate(
        'tarka_local',
        'Tarka Local: Exeter–Crediton–Yeoford–Eggesford–Barnstaple',
        'passenger',
        'local',
        ['EXD', 'CDI', 'YEO', 'EGG', 'BNP'],
        fare_per_km=0.082,
        target_headway_s=3600,
        grace_pct=0.10,
    ),
    ServiceTemplate(
        'dart_local',
        'Dartmoor Local: Exeter–Crediton–Okehampton',
        'passenger',
        'local',
        ['EXD', 'CDI', 'OKE'],
        fare_per_km=0.084,
        target_headway_s=7200,
        grace_pct=0.10,
    ),
    ServiceTemplate(
        'sw_freight',
        'SW Freight: Plymouth–Exeter–Taunton',
        'freight',
        'freight',
        ['PLY', 'EXD', 'TAU'],
        rate_per_ton_km=0.055,
        target_headway_s=10800,
        grace_pct=0.10,
    ),
    ServiceTemplate(
        'exm_local',
        'Exmouth Local: Exeter–Topsham–Exmouth',
        'passenger',
        'local',
        ['EXD', 'TOP', 'EXM'],
        fare_per_km=0.080,
        target_headway_s=1800,
        grace_pct=0.10,
    ),
    ServiceTemplate(
        'torbay_local',
        'Torbay Local: Newton Abbot–Torquay–Paignton',
        'passenger',
        'local',
        ['NWP', 'TQY', 'PGN'],
        fare_per_km=0.082,
        target_headway_s=3600,
        grace_pct=0.10,
    ),
    ServiceTemplate(
        'hon_local',
        'East Devon Local: Exeter–Honiton',
        'passenger',
        'local',
        ['EXD', 'HON'],
        fare_per_km=0.086,
        target_headway_s=3600,
        grace_pct=0.10,
    ),
]
